// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $CharLength from "./islands/CharLength.tsx";
import * as $CharSet from "./islands/CharSet.tsx";
import * as $CharSetDialog from "./islands/CharSetDialog.tsx";
import * as $Generator from "./islands/Generator.tsx";
import * as $Passwords from "./islands/Passwords.tsx";
import * as $Redirect from "./islands/Redirect.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharLength.tsx": $CharLength,
    "./islands/CharSet.tsx": $CharSet,
    "./islands/CharSetDialog.tsx": $CharSetDialog,
    "./islands/Generator.tsx": $Generator,
    "./islands/Passwords.tsx": $Passwords,
    "./islands/Redirect.tsx": $Redirect,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
